package com.creator;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class ConnectFour {
    private JButton one;
    private JButton two;
    private JButton three;
    private JButton four;
    private JButton five;
    private JButton six;
    private JButton seven;
    private JPanel pos00;
    private JPanel pos10;
    private JPanel pos20;
    private JPanel pos30;
    private JPanel pos40;
    private JPanel pos50;
    private JPanel pos01;
    private JPanel pos11;
    private JPanel pos21;
    private JPanel pos31;
    private JPanel pos41;
    private JPanel pos51;
    private JPanel pos02;
    private JPanel pos12;
    private JPanel pos22;
    private JPanel pos32;
    private JPanel pos42;
    private JPanel pos52;
    private JPanel pos03;
    private JPanel pos13;
    private JPanel pos23;
    private JPanel pos33;
    private JPanel pos43;
    private JPanel pos53;
    private JPanel pos04;
    private JPanel pos14;
    private JPanel pos24;
    private JPanel pos34;
    private JPanel pos44;
    private JPanel pos54;
    private JPanel pos05;
    private JPanel pos15;
    private JPanel pos25;
    private JPanel pos35;
    private JPanel pos45;
    private JPanel pos55;
    private JPanel pos06;
    private JPanel pos16;
    private JPanel pos26;
    private JPanel pos36;
    private JPanel pos46;
    private JPanel pos56;
    public JPanel board = new JPanel();
    public JPanel printer = new JPanel();
    private final JPanel[][] panArray = new JPanel[6][7];

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        board.setLayout(new GridLayoutManager(8, 7, new Insets(0, 0, 0, 0), 2, 2));
        board.setBackground(new Color(-12435039));
        board.setEnabled(false);
        board.setMinimumSize(new Dimension(562, 420));
        board.setPreferredSize(new Dimension(562, 420));
        one = new JButton();
        one.setBackground(new Color(-16661050));
        one.setForeground(new Color(-14670271));
        one.setHideActionText(true);
        one.setText("1");
        board.add(one, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        three = new JButton();
        three.setBackground(new Color(-16661050));
        three.setForeground(new Color(-14670271));
        three.setText("3");
        board.add(three, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        two = new JButton();
        two.setBackground(new Color(-16661050));
        two.setForeground(new Color(-14670271));
        two.setText("2");
        board.add(two, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        four = new JButton();
        four.setBackground(new Color(-16661050));
        four.setForeground(new Color(-14670271));
        four.setText("4");
        board.add(four, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        five = new JButton();
        five.setBackground(new Color(-16661050));
        five.setForeground(new Color(-14670271));
        five.setText("5");
        board.add(five, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        six = new JButton();
        six.setBackground(new Color(-16661050));
        six.setForeground(new Color(-14670271));
        six.setText("6");
        board.add(six, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        seven = new JButton();
        seven.setBackground(new Color(-16661050));
        seven.setForeground(new Color(-14670271));
        seven.setText("7");
        board.add(seven, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pos00 = new JPanel();
        pos00.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos00.setBackground(new Color(-14670271));
        board.add(pos00, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos10 = new JPanel();
        pos10.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos10.setBackground(new Color(-14670271));
        board.add(pos10, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos20 = new JPanel();
        pos20.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos20.setBackground(new Color(-14670271));
        board.add(pos20, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos30 = new JPanel();
        pos30.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos30.setBackground(new Color(-14670271));
        board.add(pos30, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos40 = new JPanel();
        pos40.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos40.setBackground(new Color(-14670271));
        board.add(pos40, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos50 = new JPanel();
        pos50.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos50.setBackground(new Color(-14670271));
        board.add(pos50, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos11 = new JPanel();
        pos11.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos11.setBackground(new Color(-14670271));
        board.add(pos11, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos01 = new JPanel();
        pos01.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos01.setBackground(new Color(-14670271));
        board.add(pos01, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos21 = new JPanel();
        pos21.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos21.setBackground(new Color(-14670271));
        board.add(pos21, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos31 = new JPanel();
        pos31.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos31.setBackground(new Color(-14670271));
        board.add(pos31, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos41 = new JPanel();
        pos41.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos41.setBackground(new Color(-14670271));
        board.add(pos41, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos51 = new JPanel();
        pos51.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos51.setBackground(new Color(-14670271));
        board.add(pos51, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos02 = new JPanel();
        pos02.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos02.setBackground(new Color(-14670271));
        board.add(pos02, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos12 = new JPanel();
        pos12.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos12.setBackground(new Color(-14670271));
        board.add(pos12, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos22 = new JPanel();
        pos22.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos22.setBackground(new Color(-14670271));
        board.add(pos22, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos32 = new JPanel();
        pos32.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos32.setBackground(new Color(-14670271));
        board.add(pos32, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos42 = new JPanel();
        pos42.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos42.setBackground(new Color(-14670271));
        board.add(pos42, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos52 = new JPanel();
        pos52.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos52.setBackground(new Color(-14670271));
        board.add(pos52, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos03 = new JPanel();
        pos03.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos03.setBackground(new Color(-14670271));
        board.add(pos03, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos13 = new JPanel();
        pos13.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos13.setBackground(new Color(-14670271));
        board.add(pos13, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos23 = new JPanel();
        pos23.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos23.setBackground(new Color(-14670271));
        board.add(pos23, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos33 = new JPanel();
        pos33.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos33.setBackground(new Color(-14670271));
        pos33.setForeground(new Color(-4473925));
        board.add(pos33, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos43 = new JPanel();
        pos43.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos43.setBackground(new Color(-14670271));
        board.add(pos43, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos53 = new JPanel();
        pos53.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos53.setBackground(new Color(-14670271));
        board.add(pos53, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos04 = new JPanel();
        pos04.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos04.setBackground(new Color(-14670271));
        board.add(pos04, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, true));
        pos14 = new JPanel();
        pos14.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos14.setBackground(new Color(-14670271));
        board.add(pos14, new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos24 = new JPanel();
        pos24.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos24.setBackground(new Color(-14670271));
        board.add(pos24, new GridConstraints(3, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, true));
        pos34 = new JPanel();
        pos34.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos34.setBackground(new Color(-14670271));
        board.add(pos34, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos44 = new JPanel();
        pos44.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos44.setBackground(new Color(-14670271));
        board.add(pos44, new GridConstraints(5, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos54 = new JPanel();
        pos54.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos54.setBackground(new Color(-14670271));
        board.add(pos54, new GridConstraints(6, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos45 = new JPanel();
        pos45.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos45.setBackground(new Color(-14670271));
        board.add(pos45, new GridConstraints(5, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos55 = new JPanel();
        pos55.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos55.setBackground(new Color(-14670271));
        board.add(pos55, new GridConstraints(6, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos35 = new JPanel();
        pos35.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos35.setBackground(new Color(-14670271));
        board.add(pos35, new GridConstraints(4, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos25 = new JPanel();
        pos25.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos25.setBackground(new Color(-14670271));
        board.add(pos25, new GridConstraints(3, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos15 = new JPanel();
        pos15.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos15.setBackground(new Color(-14670271));
        board.add(pos15, new GridConstraints(2, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos05 = new JPanel();
        pos05.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos05.setBackground(new Color(-14670271));
        board.add(pos05, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos06 = new JPanel();
        pos06.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos06.setBackground(new Color(-14670271));
        board.add(pos06, new GridConstraints(1, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos16 = new JPanel();
        pos16.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos16.setBackground(new Color(-14670271));
        board.add(pos16, new GridConstraints(2, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos26 = new JPanel();
        pos26.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos26.setBackground(new Color(-14670271));
        board.add(pos26, new GridConstraints(3, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos36 = new JPanel();
        pos36.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos36.setBackground(new Color(-14670271));
        board.add(pos36, new GridConstraints(4, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos46 = new JPanel();
        pos46.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos46.setBackground(new Color(-14670271));
        board.add(pos46, new GridConstraints(5, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        pos56 = new JPanel();
        pos56.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pos56.setBackground(new Color(-14670271));
        board.add(pos56, new GridConstraints(6, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(70, 50), new Dimension(70, 50), new Dimension(70, 50), 0, false));
        printer.setBackground(new Color(-16661050));
        Font printerFont = this.$$$getFont$$$("Arial Black", Font.BOLD, 48, printer.getFont());
        if (printerFont != null) printer.setFont(printerFont);
        printer.setForeground(new Color(-14670271));
        printer.setInheritsPopupMenu(false);
        printer.setName("The Winner is...");
        printer.setToolTipText("The Winner is...");
        printer.setVerifyInputWhenFocusTarget(true);
        printer.setVisible(true);
        board.add(printer, new GridConstraints(7, 2, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(200, 50), new Dimension(200, 50), new Dimension(200, 50), 0, false));
        printer.setBorder(BorderFactory.createTitledBorder(null, "The Winner is...", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$("Arial Black", Font.BOLD, 18, printer.getFont()), new Color(-14670271)));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return board;
    }

    public JPanel[][] getArray() {
        panArray[0][0] = pos00;
        panArray[0][1] = pos01;
        panArray[0][2] = pos02;
        panArray[0][3] = pos03;
        panArray[0][4] = pos04;
        panArray[0][5] = pos05;
        panArray[0][6] = pos06;
        panArray[1][0] = pos10;
        panArray[1][1] = pos11;
        panArray[1][2] = pos12;
        panArray[1][3] = pos13;
        panArray[1][4] = pos14;
        panArray[1][5] = pos15;
        panArray[1][6] = pos16;
        panArray[2][0] = pos20;
        panArray[2][1] = pos21;
        panArray[2][2] = pos22;
        panArray[2][3] = pos23;
        panArray[2][4] = pos24;
        panArray[2][5] = pos25;
        panArray[2][6] = pos26;
        panArray[3][0] = pos30;
        panArray[3][1] = pos31;
        panArray[3][2] = pos32;
        panArray[3][3] = pos33;
        panArray[3][4] = pos34;
        panArray[3][5] = pos35;
        panArray[3][6] = pos36;
        panArray[4][0] = pos40;
        panArray[4][1] = pos41;
        panArray[4][2] = pos42;
        panArray[4][3] = pos43;
        panArray[4][4] = pos44;
        panArray[4][5] = pos45;
        panArray[4][6] = pos46;
        panArray[5][0] = pos50;
        panArray[5][1] = pos51;
        panArray[5][2] = pos52;
        panArray[5][3] = pos53;
        panArray[5][4] = pos54;
        panArray[5][5] = pos55;
        panArray[5][6] = pos56;
        return panArray;
    }

    public JButton getOne() {
        return one;
    }

    public JButton getTwo() {
        return two;
    }

    public JButton getThree() { return three; }

    public JButton getFour() {
        return four;
    }

    public JButton getFive() {
        return five;
    }

    public JButton getSix() {
        return six;
    }

    public JButton getSeven() { return seven; }

    public JPanel getPrinter() { return printer; }
}
